Param(
  [string]$ApiKey = "3",
  [string]$LeagueId = "4328",
  [int]$KeepPast = 220,
  [int]$KeepUpcoming = 80,
  [string]$OutFile = "leagueCache.js"
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

function Get-ApiBase([string]$Key) {
  return "https://www.thesportsdb.com/api/v1/json/$Key"
}

function To-MinEvent($e) {
  return [ordered]@{
    idEvent            = $e.idEvent
    strSport           = $e.strSport
    idLeague           = $e.idLeague
    strLeague          = $e.strLeague
    strSeason          = $e.strSeason
    dateEvent          = $e.dateEvent
    strTime            = $e.strTime
    strTimestamp       = $e.strTimestamp
    strHomeTeam        = $e.strHomeTeam
    strAwayTeam        = $e.strAwayTeam
    idHomeTeam         = $e.idHomeTeam
    idAwayTeam         = $e.idAwayTeam
    intHomeScore       = $e.intHomeScore
    intAwayScore       = $e.intAwayScore
    strVenue           = $e.strVenue
    strStatus          = $e.strStatus
    strHomeGoalDetails = $e.strHomeGoalDetails
    strAwayGoalDetails = $e.strAwayGoalDetails
  }
}

$base = Get-ApiBase $ApiKey

Write-Host "Fetching league info... (LeagueId=$LeagueId, ApiKey=$ApiKey)"
$leagueInfo = Invoke-RestMethod -Uri "$base/lookupleague.php?id=$LeagueId" -TimeoutSec 30
$season = $leagueInfo.leagues[0].strCurrentSeason
if (-not $season) { throw "Missing strCurrentSeason from lookupleague" }

Write-Host "Fetching season events... (Season=$season)"
function Get-EventTimeMs($e) {
  try {
    $t = [DateTime]::Parse("$($e.dateEvent)T$($e.strTime)")
    return [int64]([DateTimeOffset]$t).ToUnixTimeMilliseconds()
  } catch {
    return 0
  }
}

function Get-Round([int]$r) {
  Start-Sleep -Milliseconds 550
  $roundData = Invoke-RestMethod -Uri "$base/eventsround.php?id=$LeagueId&r=$r&s=$season" -TimeoutSec 30
  $evs = @()
  if ($roundData.events) { $evs = @($roundData.events) }
  $times = @($evs | ForEach-Object { Get-EventTimeMs $_ } | Where-Object { $_ -gt 0 })
  $maxT = 0
  if ($times.Count -gt 0) { $maxT = ($times | Measure-Object -Maximum).Maximum }
  return [ordered]@{ r = $r; events = $evs; maxT = [int64]$maxT }
}

function Find-LastRound([int]$maxCap) {
  $lo = 1
  $hi = $maxCap
  $last = 1
  while ($lo -le $hi) {
    $mid = [int][Math]::Floor(($lo + $hi) / 2)
    $info = Get-Round $mid
    if ($info.events.Count -gt 0) {
      $last = $mid
      $lo = $mid + 1
    } else {
      $hi = $mid - 1
    }
  }
  return $last
}

function Find-AnchorRound([int]$lastRound, [int64]$nowMs) {
  $lo = 1
  $hi = $lastRound
  $ans = $lastRound
  while ($lo -le $hi) {
    $mid = [int][Math]::Floor(($lo + $hi) / 2)
    $info = Get-Round $mid
    if ($info.maxT -ge $nowMs -and $info.events.Count -gt 0) {
      $ans = $mid
      $hi = $mid - 1
    } else {
      $lo = $mid + 1
    }
  }
  return $ans
}

$maxCap = 60
$nowMs = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
$lastRound = Find-LastRound $maxCap
$anchor = Find-AnchorRound $lastRound $nowMs

$wanted = New-Object 'System.Collections.Generic.HashSet[int]'
for ($r = $anchor - 8; $r -le $anchor + 3; $r++) {
  if ($r -ge 1 -and $r -le $lastRound) { [void]$wanted.Add($r) }
}
for ($r = $lastRound - 2; $r -le $lastRound; $r++) {
  if ($r -ge 1 -and $r -le $lastRound) { [void]$wanted.Add($r) }
}

$rounds = $wanted | Sort-Object
$events = @()
foreach ($r in $rounds) {
  $info = Get-Round $r
  $events += $info.events
}

$events = $events | Group-Object idEvent | ForEach-Object { $_.Group[0] }

$past = @()
$upcoming = @()
foreach ($e in $events) {
  $hs = $e.intHomeScore
  $as = $e.intAwayScore
  $finished = ($null -ne $hs -and $null -ne $as -and "$hs" -match '^\d+$' -and "$as" -match '^\d+$')
  if ($finished) {
    $past += $e
    continue
  }
  $t = Get-EventTimeMs $e
  if ($t -ge $nowMs) { $upcoming += $e }
}

$past = $past | Sort-Object @{Expression = { Get-EventTimeMs $_ }; Descending = $true} | Select-Object -First $KeepPast
$upcoming = $upcoming | Sort-Object @{Expression = { Get-EventTimeMs $_ }; Descending = $false} | Select-Object -First $KeepUpcoming

$minPast = @($past | ForEach-Object { To-MinEvent $_ })
$minUpcoming = @($upcoming | ForEach-Object { To-MinEvent $_ })

$cache = [ordered]@{
  provider       = "TheSportsDB"
  leagueId       = "$LeagueId"
  sport          = "Soccer"
  season         = "$season"
  fetchedAt      = (Get-Date).ToString("o")
  upcomingEvents = $minUpcoming
  pastEvents     = $minPast
  _note          = "Auto-generated by tools/update-cache.ps1"
}

$json = $cache | ConvertTo-Json -Depth 8 -Compress
$js = "window.__FALLBACK_CACHE__ = $json;"

Set-Content -Path $OutFile -Value $js -Encoding UTF8
Write-Host "Wrote $OutFile"
Write-Host ("Past: {0} | Upcoming: {1}" -f $minPast.Count, $minUpcoming.Count)
