Param(
  [string]$Token = "",
  [string]$Competition = "PL",
  [int]$KeepPast = 220,
  [int]$KeepUpcoming = 80,
  [switch]$IncludeSquads = $true,
  [string]$OutFile = "leagueCache.js"
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

if (-not $Token) { $Token = $env:FOOTBALL_DATA_TOKEN }
if (-not $Token) { throw "Missing Token. Pass -Token or set env:FOOTBALL_DATA_TOKEN" }

$base = "https://api.football-data.org/v4"
$headers = @{ "X-Auth-Token" = $Token }

function Invoke-FD([string]$Path) {
  return Invoke-RestMethod -Uri ($base + $Path) -Headers $headers -TimeoutSec 30
}

function To-MinEvent($m, $comp) {
  $utc = [DateTime]::Parse($m.utcDate).ToUniversalTime()
  $date = $utc.ToString("yyyy-MM-dd")
  $time = $utc.ToString("HH:mm:ss")
  $hs = $m.score.fullTime.home
  $as = $m.score.fullTime.away
  $finished = ($m.status -eq "FINISHED" -and $null -ne $hs -and $null -ne $as)
  return [ordered]@{
    idEvent            = "fd:$($m.id)"
    strSport           = "Soccer"
    idLeague           = "$($comp.code)"
    strLeague          = "$($comp.name)"
    strSeason          = "$($comp.currentSeason.startDate.Substring(0,4))"
    dateEvent          = $date
    strTime            = $time
    strTimestamp       = $utc.ToString("o")
    strHomeTeam        = $m.homeTeam.name
    strAwayTeam        = $m.awayTeam.name
    idHomeTeam         = "$($m.homeTeam.id)"
    idAwayTeam         = "$($m.awayTeam.id)"
    intHomeScore       = $(if ($finished) { "$hs" } else { $null })
    intAwayScore       = $(if ($finished) { "$as" } else { $null })
    strVenue           = $null
    strStatus          = $m.status
    strHomeGoalDetails = $null
    strAwayGoalDetails = $null
  }
}

Write-Host "Fetching competition... ($Competition)"
$comp = Invoke-FD "/competitions/$Competition"
$seasonYear = $comp.currentSeason.startDate.Substring(0,4)

Write-Host "Fetching matches... (season=$seasonYear)"
$matches = Invoke-FD "/competitions/$Competition/matches?season=$seasonYear"
$all = @()
if ($matches.matches) { $all = @($matches.matches) }

$minEvents = @($all | ForEach-Object { To-MinEvent $_ $comp })

function Get-EventTimeMs($e) {
  try {
    $t = [DateTime]::Parse("$($e.dateEvent)T$($e.strTime)Z").ToUniversalTime()
    return [int64]([DateTimeOffset]$t).ToUnixTimeMilliseconds()
  } catch {
    return 0
  }
}

$nowMs = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
$past = @()
$upcoming = @()
foreach ($e in $minEvents) {
  $finished = ($null -ne $e.intHomeScore -and $null -ne $e.intAwayScore)
  if ($finished) { $past += $e; continue }
  $t = Get-EventTimeMs $e
  if ($t -ge $nowMs) { $upcoming += $e }
}

$past = $past | Sort-Object @{Expression = { Get-EventTimeMs $_ }; Descending = $true} | Select-Object -First $KeepPast
$upcoming = $upcoming | Sort-Object @{Expression = { Get-EventTimeMs $_ }; Descending = $false} | Select-Object -First $KeepUpcoming

Write-Host "Fetching scorers... (season=$seasonYear)"
$scorers = @()
try {
  $sc = Invoke-FD "/competitions/$Competition/scorers?season=$seasonYear"
  if ($sc.scorers) { $scorers = @($sc.scorers) }
} catch {
  Write-Host "Scorers not available on this plan; continuing..."
}

$playerGoals = @{}
foreach ($s in $scorers) {
  $teamId = "$($s.team.id)"
  if (-not $playerGoals.ContainsKey($teamId)) { $playerGoals[$teamId] = @{} }
  $name = $s.player.name
  $goals = [int]($s.goals)
  $playerGoals[$teamId][$name] = $goals
}

$teamSquads = @{}
if ($IncludeSquads) {
  $teamIds = New-Object 'System.Collections.Generic.HashSet[string]'
  foreach ($e in @($past + $upcoming)) {
    [void]$teamIds.Add("$($e.idHomeTeam)")
    [void]$teamIds.Add("$($e.idAwayTeam)")
  }

  $i = 0
  foreach ($tid in ($teamIds | Sort-Object)) {
    $i++
    Start-Sleep -Milliseconds 550
    try {
      $t = Invoke-FD "/teams/$tid"
      $squad = @()
      if ($t.squad) {
        $squad = @($t.squad | ForEach-Object {
          [ordered]@{
            name     = $_.name
            position = $(if ($_.position) { $_.position } else { "—" })
          }
        })
      }
      $teamSquads[$tid] = $squad
      Write-Host ("Squad {0}/{1} ok (teamId={2})" -f $i, $teamIds.Count, $tid)
    } catch {
      Write-Host ("Squad {0}/{1} failed (teamId={2})" -f $i, $teamIds.Count, $tid)
    }
  }
}

$cache = [ordered]@{
  provider       = "Football-Data.org"
  leagueId       = "$Competition"
  sport          = "Soccer"
  season         = "$seasonYear"
  fetchedAt      = (Get-Date).ToString("o")
  upcomingEvents = @($upcoming)
  pastEvents     = @($past)
  playerGoals    = $playerGoals
  teamSquads     = $teamSquads
  _note          = "Auto-generated by tools/update-cache-footballdata.ps1"
}

$json = $cache | ConvertTo-Json -Depth 10 -Compress
$js = "window.__FALLBACK_CACHE__ = $json;"
Set-Content -Path $OutFile -Value $js -Encoding UTF8

Write-Host "Wrote $OutFile"
Write-Host ("Past: {0} | Upcoming: {1} | Teams(with squads): {2}" -f $past.Count, $upcoming.Count, $teamSquads.Keys.Count)

